name: CI/CD
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  ci-python-test:
    name: "Test CI Python app"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "pypy3.9"

      - name: Install Python dependencies
        run: |
          cd ./app/python
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittest on code
        run: |
          cd ./app/python
          python -m unittest test_main.py

  cd-python-deployment:
    name: "Deploy Three Tier Application"
    runs-on: ubuntu-latest
    if: contains('refs/heads/master', github.ref)
    needs: ci-python-test
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/privkey.pem
          echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/privkey.pem
          chmod 400 /home/runner/.ssh/privkey.pem
      - name: Run Ansible playbook
        shell: bash
        run: |
          service ssh status
          sudo apt install ansible --yes
          ansible-playbook -i inventory -l database final-playbook.yml
          ansible-playbook -i inventory -l backend final-playbook.yml
          ansible-playbook -i inventory -l frontend final-playbook.yml