# use the git module to clone a repository
# install the necessary dependencies
# Run the program
---
- name: Deploy
  hosts:
    - webservers
  become: true
  
  tasks:    
    - name: Install git onto host
      ansible.builtin.apt:
        name: git
        update_cache: yes
    - name: Clone Python repository
      ansible.builtin.git:
        repo: https://github.com/alanbchristie/PySimple.git
        dest: /home/ubuntu/pysimple
    # - name: Install pip on remote
    #   ansible.builtin.apt:
    #     name: python3-pip
    # - name: Install Python Requirements
    #   ansible.builtin.pip:
    #     requirements: /home/ubuntu/python/requirements.txt
    # - name: Run Python application in background
    #   ansible.builtin.shell:
    #     cmd: |
    #       PYTHON_PID=$(lsof -t -i :8080)
    #       if [ -z "$PYTHON_PID" ]
    #       then
    #         echo "Process has not started yet"
    #       else
    #         echo "Killing process before starting again"
    #         kill $PYTHON_PID
    #       fi

    #       python3 main.py
    #     chdir: /home/ubuntu/python
    #   async: 10
    #   poll: 0
